apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: mern-ecommerce-ns
spec:
  selector:
    app: client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30007
  type: NodePort