apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: mern-ecommerce-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: exenyx7/mern-ecommerce-client:latest
        ports:
        - containerPort: 8080