apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: mern-ecommerce-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mern-ecommerce-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: mern-ecommerce-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: exenyx7/mern-ecommerce-server:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: BASE_API_URL
          value: "api"
        - name: CLIENT_URL
          value: "http://client-service"
        - name: JWT_SECRET
          value: "update_your_JWT_secret"
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/mern_ecommerce"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: mern-ecommerce-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: exenyx7/mern-ecommerce-client:latest
        ports:
        - containerPort: 8080