apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mern-ecommerce-ns
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: mern-ecommerce-ns
spec:
  selector:
    app: server
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: mern-ecommerce-ns
spec:
  type: NodePort
  selector:
    app: client
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30007