apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: mern-ecommerce-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: exenyx7/mern-ecommerce-server:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: BASE_API_URL
          value: "api"
        - name: CLIENT_URL
          value: "http://client:80"
        - name: JWT_SECRET
          value: "update_your_JWT_secret"
        - name: MONGO_URI
          value: "mongodb://mongodb.mern-ecommerce-ns:27017/mern_ecommerce"
        # Remove readiness/liveness probes temporarily until the app is working
        # command section modified for troubleshooting
        command: ["/bin/sh", "-c"]
        args: 
        - |
          echo "Waiting for MongoDB to start..."
          sleep 10
          echo "Starting server..."
          npm start
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: mern-ecommerce-ns
spec:
  selector:
    app: server
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP