name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      shell: bash
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $("C:/Program Files/Kubernetes/Minikube/minikube.exe" docker-env --shell=bash)

    - name: Build Client Docker image
      run: |
        cd app/client
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-client:latest .

    - name: Build Server Docker image
      run: |
        cd app/server
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-server:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker images to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-client:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-server:latest

    - name: Update deployment image
      shell: bash
      run: |
        # Update deployment.yaml with the Docker Hub username
        cd app
        sed -i "s|exenyx7/mern-ecommerce-client:latest|${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-client:latest|g" deployment.yaml
        sed -i "s|exenyx7/mern-ecommerce-server:latest|${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-server:latest|g" deployment.yaml

    - name: Deploy to Minikube
      run: |
        cd app
        kubectl apply -f namespace.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    - name: Verify deployment
      shell: powershell
      run: |
        echo "Waiting for deployments to be ready..."
        kubectl wait --for=condition=available --timeout=300s deployment/client -n mern-ecommerce-ns
        kubectl wait --for=condition=available --timeout=300s deployment/server -n mern-ecommerce-ns
        kubectl wait --for=condition=available --timeout=300s deployment/mongodb -n mern-ecommerce-ns
        
        echo "Displaying all resources in namespace:"
        kubectl get all -n mern-ecommerce-ns
        
        echo "Getting application URL..."
        # Get the NodePort directly instead of using minikube service command
        $NODE_PORT = kubectl get service client-service -n mern-ecommerce-ns -o jsonpath="{.spec.ports[0].nodePort}"
        $MINIKUBE_IP = (& "C:/Program Files/Kubernetes/Minikube/minikube.exe" ip)
        echo "Application is available at: http://${MINIKUBE_IP}:${NODE_PORT}"
        
        # Set up port forwarding as fallback
        echo "Setting up port forwarding to access application at http://localhost:8080"
        Start-Process -NoNewWindow powershell -ArgumentList "kubectl port-forward service/client-service 8080:80 -n mern-ecommerce-ns"