name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      shell: powershell
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        # Get Minikube Docker environment variables and execute them in PowerShell
        minikube docker-env | Foreach-Object {
          if ($_ -match '^\s*export (.+?)=(.+)$') {
            $var = $Matches[1]
            $value = $Matches[2].Trim('"')
            echo "Setting $var=$value"
            [Environment]::SetEnvironmentVariable($var, $value)
          }
        }

    - name: Build Client Docker image
      shell: powershell
      run: |
        cd app/client
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-client:latest .

    - name: Build Server Docker image
      shell: powershell
      run: |
        cd app/server
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-server:latest .

    - name: Login to Docker Hub
      shell: powershell
      run: |
        $password = "${{ secrets.DOCKER_PASSWORD }}"
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential ("${{ secrets.DOCKER_USERNAME }}", $securePassword)
        docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin <<< $password

    - name: Push Docker images to Docker Hub
      shell: powershell
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-client:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-server:latest

    - name: Update deployment image
      shell: powershell
      run: |
        # Update deployment.yaml with the Docker Hub username
        cd app
        (Get-Content -Path deployment.yaml) -replace 'exenyx7/mern-ecommerce-client:latest', '${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-client:latest' | Set-Content -Path deployment.yaml
        (Get-Content -Path deployment.yaml) -replace 'exenyx7/mern-ecommerce-server:latest', '${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-server:latest' | Set-Content -Path deployment.yaml

    - name: Deploy to Minikube
      shell: powershell
      run: |
        cd app
        kubectl apply -f namespace.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    - name: Verify deployment
      shell: powershell
      run: |
        echo "Waiting for deployments to be ready..."
        kubectl wait --for=condition=available --timeout=300s deployment/client -n mern-ecommerce-ns
        kubectl wait --for=condition=available --timeout=300s deployment/server -n mern-ecommerce-ns
        kubectl wait --for=condition=available --timeout=300s deployment/mongodb -n mern-ecommerce-ns
        
        echo "Displaying all resources in namespace:"
        kubectl get all -n mern-ecommerce-ns
        
        echo "Getting application URL..."
        $NodePort = (kubectl get service client-service -n mern-ecommerce-ns -o jsonpath="{.spec.ports[0].nodePort}")
        $MinikubeIP = (minikube ip)
        echo "Application is available at: http://${MinikubeIP}:${NodePort}"