name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        # PowerShell version of minikube docker-env
        & minikube -p minikube docker-env --shell powershell | Invoke-Expression

    - name: Build Client Docker image
      run: |
        cd app/client
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-client:latest .

    - name: Build Server Docker image
      run: |
        cd app/server
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-server:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker images to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-client:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-server:latest

    - name: Update deployment image
      run: |
        # Update deployment.yaml with the Docker Hub username
        cd app
        (Get-Content deployment.yaml) -replace 'exenyx7/mern-ecommerce-client:latest', '${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-client:latest' | Set-Content deployment.yaml
        (Get-Content deployment.yaml) -replace 'exenyx7/mern-ecommerce-server:latest', '${{ secrets.DOCKER_USERNAME }}/mern-ecommerce-server:latest' | Set-Content deployment.yaml

    - name: Deploy to Minikube
      run: |
        cd app
        kubectl apply -f namespace.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    - name: Verify deployment
      run: |
        echo "Waiting for deployments to be ready..."
        kubectl wait --for=condition=available --timeout=60s deployment/client -n mern-ecommerce-ns
        kubectl wait --for=condition=available --timeout=60s deployment/server -n mern-ecommerce-ns
        kubectl wait --for=condition=available --timeout=60s deployment/mongodb -n mern-ecommerce-ns
        
        echo "Displaying all resources in namespace:"
        kubectl get all -n mern-ecommerce-ns
        
        echo "----------------------------------------"
        echo "ACCESS OPTIONS:"
        echo "1. Run this command in a separate terminal to create a tunnel:"
        echo "   minikube service client-service -n mern-ecommerce-ns"
        echo ""
        echo "2. Or set up port forwarding:"
        echo "   kubectl port-forward service/client-service 8080:80 -n mern-ecommerce-ns"
        echo "   Then access: http://localhost:8080"
        echo "----------------------------------------"



        echo "Minikube status:"
        minikube status


      continue-on-error: true  # Allow workflow to complete even if this step fails