name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)
    
    - name: Build client Docker image
      run: |
        docker build -t exenyx7/mern-ecommerce-client:latest ./client
    
    - name: Build server Docker image
      run: |
        docker build -t exenyx7/mern-ecommerce-server:latest ./server
    
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Push client Docker image to Docker Hub
      run: docker push exenyx7/mern-ecommerce-client:latest
    
    - name: Push server Docker image to Docker Hub
      run: docker push exenyx7/mern-ecommerce-server:latest
    
    - name: Deploy to Minikube
      run: |
        kubectl apply -f namespace.yaml
        kubectl apply -f mongodb-deployment.yaml
        kubectl apply -f server-deployment.yaml
        kubectl apply -f client-deployment.yaml